package modelo;
// Generated 21 ene 2026, 13:48:14 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties; // <--- 1. IMPORT NUEVO
import com.google.gson.annotations.Expose;

/**
 * Tipos generated by hbm2java
 */
// 👇 2. ETIQUETA NUEVA (Anti-Fantasma) 👇
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Tipos implements java.io.Serializable {

	@Expose private Integer id;
	@Expose private String name;
	private String nameEu;
	private transient Set userses = new HashSet(0);

	public Tipos() {
	}

	public Tipos(String name) {
		this.name = name;
	}

	public Tipos(String name, String nameEu, Set userses) {
		this.name = name;
		this.nameEu = nameEu;
		this.userses = userses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNameEu() {
		return this.nameEu;
	}

	public void setNameEu(String nameEu) {
		this.nameEu = nameEu;
	}

	@JsonIgnore
	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

}